# Generated by Django 6.0.3 on 2026-03-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('born', models.PositiveIntegerField()),
                ('died', models.PositiveIntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_photos/')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='genealogy.familymember')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='genealogy.familymember')),
            ],
            options={
                'ordering': ['born', 'name'],
            },
        ),
    ]
