# Generated by Django 6.0.3 on 2026-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='genealogy.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='born',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
